use diagprint::{
    Applicability, DiagnosticReport, ReportStatus, Reporter, Severity, SeverityCounts, Suggestion,
};
use diagprint_test::prelude::*;

fn reporter() -> Reporter {
    Reporter::builder()
        .application("diagprint-test")
        .color(false)
        .build()
        .expect("test reporter should build")
}

#[test]
fn diagnostic_assertions_cover_structured_fields() {
    let reporter = reporter();

    let diagnostic = reporter
        .warning("unused binding detected")
        .code("lint::unused")
        .attribute("pass", 2_u64)
        .note("generated by parser")
        .help("remove the unused binding")
        .label("src/main.rs", 7, Some(5), Some(3), Some("unused here"))
        .suggestion(
            Suggestion::new("Remove binding").applicability(Applicability::MachineApplicable),
        );

    diagnostic
        .assert_severity(Severity::Warning)
        .assert_code("lint::unused")
        .assert_message_contains("unused binding")
        .assert_attribute("pass", 2_u64)
        .assert_note_contains("parser")
        .assert_help_contains("remove")
        .assert_primary_label("src/main.rs", 7)
        .assert_suggestion("Remove binding")
        .assert_suggestion_applicability("Remove binding", Applicability::MachineApplicable);
}

#[test]
fn report_assertions_cover_status_counts_and_contents() {
    let reporter = reporter();

    let mut report = DiagnosticReport::new();

    report
        .push(
            reporter
                .info("analysis complete")
                .code("analysis::complete"),
        )
        .push(reporter.error("parse failed").code("parse::failed"));

    report
        .assert_len(2)
        .assert_not_empty()
        .assert_status(ReportStatus::Failure)
        .assert_counts(SeverityCounts {
            info: 1,
            error: 1,
            ..SeverityCounts::default()
        })
        .assert_contains_severity(Severity::Info)
        .assert_contains_severity(Severity::Error)
        .assert_contains_code("parse::failed")
        .assert_count_at_or_above(Severity::Warning, 1);
}

#[test]
fn empty_report_assertions_work() {
    DiagnosticReport::new()
        .assert_empty()
        .assert_status(ReportStatus::Success)
        .assert_none_at_or_above(Severity::Trace);
}

#[test]
#[should_panic(expected = "diagnostic code mismatch")]
fn assertion_failures_explain_the_mismatch() {
    reporter()
        .error("boom")
        .code("actual")
        .assert_code("expected");
}
