//! # diagprint
//!
//! `diagprint` provides structured diagnostics, rich terminal rendering,
//! persistent reports, guarded remediation, and diagnostic-intelligence
//! integrations for Rust applications.
//!
//! The crate deliberately separates diagnostic data from presentation and
//! mutation:
//!
//! - [`Diagnostic`] describes what happened.
//! - renderers decide how the diagnostic is displayed.
//! - [`Suggestion`] describes a possible resolution.
//! - [`Fixer`] validates and optionally applies structured text edits.
//! - [`DiagnosticMetadata`] lets typed errors contribute reliable semantic
//!   information without parsing formatted error strings.
//!
//! Calling a renderer never modifies source files.
//!
//! ## Quick start
//!
//! ```
//! use diagprint::{Reporter, Severity};
//!
//! # fn main() -> diagprint::Result<()> {
//! let reporter = Reporter::builder()
//!     .application("myapp")
//!     .min_severity(Severity::Info)
//!     .build()?;
//!
//! let diagnostic = reporter
//!     .error("Network initialization failed")
//!     .code("NET-001")
//!     .cause("failed to open network interface")
//!     .help("Check interface permissions and driver state");
//!
//! reporter.emit(&diagnostic)?;
//! # Ok(())
//! # }
//! ```
//!
//! ## Diagnostic intelligence
//!
//! Structured suggestions can carry explanations, documentation links,
//! structured edits, advisory follow-up commands, and an [`Applicability`]
//! classification.
//!
//! Automatic editing requires [`Applicability::MachineApplicable`], valid
//! non-overlapping UTF-8 edit ranges, and exact verification of the expected
//! current file contents.
//!
//! Suggested shell commands are informational only and are never executed by
//! [`Fixer`].
//!
//! ## Typed errors
//!
//! Application error enums and structs can implement [`DiagnosticMetadata`]
//! to provide stable diagnostic codes, severity, help, notes, and structured
//! suggestions.
//!
//! This works naturally with errors generated by `thiserror` because the
//! integration is based on the standard [`std::error::Error`] interface.
//!
//! ## Ecosystem integrations
//!
//! The optional `anyhow` feature preserves Anyhow context/source chains and
//! enriches recognized standard-library failures.
//!
//! The optional `tracing` feature provides a composable tracing-subscriber
//! layer that turns significant runtime events into structured diagnostics.
//! It can preserve:
//!
//! - tracing severity;
//! - structured event fields;
//! - diagnostic codes and help;
//! - active span ancestry;
//! - source locations;
//! - actual `std::error::Error` source chains.
//!
//! Integrations feed existing Rust ecosystems into `diagprint` rather than
//! requiring applications to replace them.
//!
//! ## Terminal documentation
//!
//! The optional `terminal-docs` feature can fetch documentation and display it
//! directly in a terminal with sanitized remote content and syntax-highlighted
//! examples.
//!
//! ## Themes
//!
//! [`Theme`], [`Style`], and [`SeverityTheme`] control terminal presentation.
//! Disabling renderer color remains authoritative regardless of the selected
//! theme.
//!
//! The optional `cybercore` feature maps the Cybercore semantic palette into
//! `diagprint` rather than copying Cybercore color values.
//!
//! ## Feature flags
//!
//! - `anyhow` — Anyhow context-chain integration.
//! - `tracing` — structured tracing-event integration.
//! - `compression` — gzip and Zstandard report compression.
//! - `cybercore` — Cybercore theme-schema integration.
//! - `terminal-docs` — terminal documentation retrieval and syntax
//!   highlighting.
//!
//! Typed-error metadata support is part of the core crate and does not require
//! a feature flag.
//!
//! All optional features are disabled by default.

mod diagnostic;
mod fixer;
mod intelligence;
mod reporter;
mod rotation;
mod severity;
mod suggestion;
mod typed;

#[cfg(any(feature = "anyhow", feature = "tracing"))]
pub mod integrations;

#[cfg(feature = "terminal-docs")]
pub mod docs;

pub mod render;

pub use diagnostic::{Cause, Diagnostic, Label, SourceLocation};
pub use fixer::{FixCheck, FixError, FixPreview, FixReport, Fixer};
pub use render::{SeverityTheme, Style, Theme};
pub use reporter::{Compression, Reporter, ReporterBuilder};
pub use rotation::{RotationCadence, RotationPolicy, RotationState};
pub use severity::Severity;
pub use suggestion::{
    Applicability, DocumentationLink, Edit, SuggestedCommand, Suggestion, TextRange,
};
pub use typed::{DiagnosticErrorExt, DiagnosticMetadata};

#[cfg(feature = "anyhow")]
pub use integrations::AnyhowDiagnosticExt;

#[cfg(feature = "tracing")]
pub use integrations::TracingLayer;

#[cfg(feature = "terminal-docs")]
pub use docs::{TerminalDocError, TerminalDocViewer};

/// Convenience result type used by `diagprint` reporting operations.
pub type Result<T> = std::io::Result<T>;
